# version: 0.2

# phases:
#   pre_build:
#     commands:
#       - npm install
#   build:
#     commands:
#       - npm run build
#   post_build:
#     commands:
#       - aws s3 cp --recursive ./build <bucket name>/
#       - aws cloudfront create-invalidation --distribution-id <>

# version: 0.0
# os: linux
# files:
#   - source: /index.html
#     destination: /var/www/html/
# hooks:
#   BeforeInstall:
#     - location: scripts/install_dependencies
#       timeout: 300
#       runas: root
#     - location: scripts/start_server
#       timeout: 300
#       runas: root
#   ApplicationStop:
#     - location: scripts/stop_server
#       timeout: 300
#       runas: root

version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - npm install
  test_build:
    commands:
      - echo Test started on `date`
      - npm test
  build:
    commands:
      - echo Build completed on `date`
      - npm run build     
      - ls -R build
  post_build:
    commands:
      - aws s3 cp build/ s3://demo-bucket-for-poc/ --recursive

artifacts:
  files:
    - '**/*'
  # discard-paths: no
  # base-directory: build
  
